apiVersion: v1
kind: ConfigMap
metadata:
  name: defmap
data:
  env_files.properties: |
    user=debian-sys-maint
    password= rpwrQtHNcQMuKcH8
    host= localhost
    database= employee
    raise_on_warnings= true
    auth_plugin= mysql_native_password
